In [13]:
#1.Write a Python program to Add two matrices

import numpy as np

A = np.array([[2, 4], [5, -6]])
B = np.array([[9, -3], [3, 6]])
C = A + B  
print(C)


[[11  1]
 [ 8  0]]


In [12]:
#2.Write a Python Program to Multiply Two Matrices?

import numpy as np

A = np.array([[3, 6, 7], [5, 3, 0]])
B = np.array([[1, 1], [2, 1], [3, 3]])
C = A.dot(B)
print(C)



[[36 30]
 [11  8]]


In [15]:
#3.Write a Python program to Transpose a Matrix?

import numpy as np

A = np.array([[1, 7], [2, 8], [3, 4]])
print(A.transpose())

[[1 2 3]
 [7 8 4]]


In [16]:
#4. write a Python program to Sort Words in Alphabetic Order

my_str = input("Enter a string: ")

words = [word.lower() for word in my_str.split()]
words.sort()
print("The sorted words are:")

for word in words:
    print(word)

Enter a string: this is my python program
The sorted words are:
is
my
program
python
this


In [17]:
#5.Write a Python Program to Remove Punctuation From a String?

punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''

my_str = input("Enter a string: ")

no_punct = ""
for char in my_str:
    if char not in punctuations:
        no_punct = no_punct + char

print("String after removal of punctuation:")
print(no_punct)


Enter a string: ''hello'!(python)-[program]{};:'"\
String after removal of punctuation:
hellopythonprogram
